version: '3.8'
services:
  web:
    container_name: BioTrackrAPP
    build: .
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:rootpass@mongo:27017/?authSource=admin
      - MONGODB_DB=BIOREN
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: BioTrackrDB
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=BIOREN
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
